name: Upload caj2pdf to GitHub Actions Artifacts
on:
  workflow_dispatch:
  push:
    branches:
      - 'releases/**'

jobs:
  windows_pub:
    name: Publish from Windows Server 2019
    runs-on: windows-2019
    steps:
    - name: Fetch Source Code
      uses: actions/checkout@v2
      with:
        lfs: true
        fetch-depth: 1
    - name: Setup Python 3
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Python Dependencies
      run: |
        python -m pip install -U pip && pip install pdm
        pdm install
    - name: Build Package
      run: pdm build --no-sdist
    - name: Upload to github action artifact
      uses: actions/upload-artifact@v3
      with:
        path: dist/*.whl

  linux_pub:
    name: Publish from Ubuntu, no JBIG2DEC
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Source Code
      uses: actions/checkout@v2
      with:
        lfs: true
        fetch-depth: 1
    - name: Setup Python 3
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Python Dependencies
      run: |
        python -m pip install -U pip && pip install pdm
        pdm install -d
    - name: Build Package
      run: pdm build
    - name: Get Glibc version
      run: ldd --version > dist/ldd.version.txt
    - name: Upload to github action artifact
      uses: actions/upload-artifact@v3
      with:
        path: |
          dist/*.whl
          dist/*.tar.gz
          dist/ldd.version.txt
