name: Test caj2pdf bin
on:
  push:
    branches:
      - dev

jobs:
  test_ubuntu:
    strategy:
      matrix:
        ubuntu-version: ["ubuntu-20.04"]
        python-version: ["3.10"]
        dep-lib: ["libpoppler-dev"]
        # dep-lib: ["libpoppler-dev", "libjbig2dec0-dev"] # libjbig2dec in Ubuntu has lots of problems.
        # src-caj: ["caj", "kdh"]
        src-caj: ["c8", "caj", "hn", "kdh"] # only caj, kdh in sample successed
    name: Test on ${{ matrix.ubuntu-version }}
    runs-on: ${{ matrix.ubuntu-version }}
    steps:
    - name: Fetch Source Code
      uses: actions/checkout@v2
      with:
        lfs: true
        fetch-depth: 1
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install C++ Dependencies
      run: sudo apt -y install build-essential ${{ matrix.dep-lib }} mupdf-tools pkg-config
    - name: Install Python Project with "poppler"
      if: ${{ matrix.dep-lib == 'libpoppler-dev' }}
      run: |
        python -m pip install -U pip && pip install pdm
        pdm install
    - name: Install Python Project with "jbig2dec"
      if: ${{ matrix.dep-lib == 'libjbig2dec0-dev' }}
      run: |
        python -m pip install -U pip && pip install pdm
        LIBJBIG2DEC=1 pdm install
    - name: Convert Test Caj
      run: pdm run caj2pdf convert tests/${{ matrix.src-caj }}_src.caj -o tests/${{ matrix.src-caj }}_dst.pdf

  test_windows:
    name: Test on Windows Server 2019
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: ["3.10"]
        # src-caj: ["caj", "kdh"]
        src-caj: ["c8", "caj", "hn", "kdh"] # only caj, kdh in sample successed
    steps:
    - name: Fetch Source Code
      uses: actions/checkout@v2
      with:
        lfs: true
        fetch-depth: 1
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python Dependencies
      run: |
        python -m pip install -U pip && pip install pdm
        pdm install
    - name: Install mutool.exe
      run: |
        curl.exe -L https://mupdf.com/downloads/archive/mupdf-1.18.0-windows.zip -o mupdf.zip
        Expand-Archive -Force mupdf.zip .
        Copy-Item mupdf-1.18.0-windows/mutool.exe C:\WINDOWS\system32\mutool.exe
      shell: pwsh
    - name: Convert Test Caj
      run: pdm run caj2pdf convert tests\\${{ matrix.src-caj }}_src.caj -o tests\\${{ matrix.src-caj }}_dst.pdf
